= Securing traffic between Service Mesh Deployments with mTLS
:toc:

== Different SMCP Setups for `STRICT` vs `PERMISSIVE` mTLS

1. SMCP without `security` section results in `PERMISSIVE` mTLS policy

	oc get PeerAuthentication -n istio-system
	NAME                            MODE         AGE
	default                         PERMISSIVE   2d
	disable-mtls-jaeger-collector   DISABLE      2d
	grafana-ports-mtls-disabled     PERMISSIVE   2d

2. SMCP with `security` section and `dataplane` mTLS enabled
** config

	spec:
	  security:
	    dataPlane:
	      mtls: true

** policies changed to `STRICT`

	NAME                            MODE         AGE
	default                         STRICT       2d
	disable-mtls-jaeger-collector   DISABLE      2d
	grafana-ports-mtls-disabled     PERMISSIVE   2d

3. Verifying mTLS is used

* Check link:https://kiali.io/docs/features/security/#masthead-indicator[KIALI for Mesh-wide mTLS enabled indicator]

* Deploy bookinfo

  oc new-project bookinfo
  oc patch smmr default --type='json' -p='[{"op": "add", "path": "/spec/members/-", "value":"bookinfo"}]' -n istio-system-certs
  oc apply -f https://raw.githubusercontent.com/maistra/istio/maistra-2.1/samples/bookinfo/platform/kube/bookinfo.yaml
  oc apply -f https://raw.githubusercontent.com/maistra/istio/maistra-2.1/samples/bookinfo/networking/bookinfo-gateway.yaml
  curl -s "http://$(oc get route istio-ingressgateway -o jsonpath='{.spec.host}' -n istio-system-certs)/productpage" | grep -o "<title>.*</title>"

4. Set different `DestinationRule` traffic.tls.mode to specify mTLS connection behavior to upstream cluster (see link:https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings-TLSmode[DestinationRule refrence])

* Options

Name		Description
DISABLE		Do not setup a TLS connection to the upstream endpoint.
SIMPLE		Originate a TLS connection to the upstream endpoint.
MUTUAL		Secure connections to the upstream using mutual TLS by presenting client certificates for authentication.
ISTIO_MUTUAL	Secure connections to the upstream using mutual TLS by presenting client certificates for authentication. Compared to Mutual mode, this mode uses certificates generated automatically by Istio for mTLS authentication. When this mode is used, all other fields in ClientTLSSettings should be empty.

* Use different rules

	oc apply -f https://raw.githubusercontent.com/maistra/istio/maistra-2.1/samples/bookinfo/networking/destination-rule-all.yaml
	oc apply -f https://github.com/maistra/istio/blob/maistra-2.1/samples/bookinfo/networking/destination-rule-all-mtls.yaml

== 1 - Service Mesh generated self-signed certificates for workload to workload communication

* As previously shown this Out-of-the-box functionality and use of it is dependent on configuration

== 2 - Adding an external certificate authority key and certificate 

* link:https://docs.openshift.com/container-platform/4.9/service_mesh/v2x/ossm-security.html#ossm-cert-manage_ossm-security[Adding an external certificate authority key and certificate]

== 3 - Use an external issuer for internal SM certs usage not supported 

* NOT SUPPORTED https://issues.redhat.com/browse/OSSM-568 


