= Scenarios for Observability Setups
:toc:


Describes different Tracing and Metrics Setups for the Service Mesh

== TRACING

=== (Default STACK) - Non Production Use

- setup
- sizing
- placement
- usage

=== (Default STACK) - Production Use

[NOTE]
====
There can be more options than those presented
====


* Resources
** link:https://docs.openshift.com/container-platform/4.8/service_mesh/v2x/ossm-reference-jaeger.html#jager-deployment-best-practices_jaeger-config-reference[Jaeger Deployment Best Practices]
** link:https://docs.openshift.com/container-platform/4.8/service_mesh/v2x/ossm-reference-jaeger.html#ossm-deploying-jaeger-production_jaeger-config-reference[Jaeger Production Setup]
** link:https://docs.openshift.com/container-platform/4.9/service_mesh/v2x/ossm-reference-jaeger.html#ossm-specifying-external-jaeger_jaeger-config-reference[Specifying Jaeger configuration in a Jaeger custom resource]
** link:https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/README.md[Jaeger Core for Workload ENV Properties]


==== DaemonSet Jaeger Agent

* setup
** Jaeger
*** Consider and apply link:https://www.jaegertracing.io/docs/1.32/operator/#openshift[pre-requisites for Jaeger Agent as DaemonSet on Openshift]
*** Jaeger Resource

	oc apply -f https://raw.githubusercontent.com/skoussou/servicemesh-playground/main/Scenario-Observability-Scenarios/jaeger-daemonset.yaml

** Service Mesh SMCP with external Jaeger Deployment

	oc apply -f https://raw.githubusercontent.com/skoussou/servicemesh-playground/main/Scenario-Observability-Scenarios/smcp-2.1-external-jaeger-resource.yaml


** Deploy Application link:https://github.com/skoussou/servicemesh-playground/tree/main/Scenario-0-Deploy-In-ServiceMesh#opentracing-with-jaeger-agent-sidecar[opentracing-hello] with opentracing configuration
*** `istio-proxy` sidecar default configuration (points *_DIRECT_* to the collector and not the agent)

----
      meshConfig:
        defaultConfig:
          tracing:
            zipkin:
              address: 'custom-prod-collector.istio-system.svc:9411'
----              

* sizing (*TBD*) for production ready
* placement (*TBD*)
* usage (*TBD*)



==== Jaeger agent as a sidecar

[NOTE]
====
Jaeger agent as a daemonset is not supported for multitenant installations or OpenShift Dedicated. Jaeger agent as a sidecar is the only supported configuration for these use cases.
====

----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  annotations:
    "sidecar.jaegertracing.io/inject": "true" # <1>
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: acme/myapp:myversion
----        

=== Custom Stack

- setup (re-direction to other Jaeger agent)
- sizing
- placement
- usage


