= Various Deployments for the ServiceMesh
:toc:

== httpbin

	oc new-project httpbin
	oc project httpbin
	oc apply -f https://raw.githubusercontent.com/maistra/istio/maistra-2.1/samples/httpbin/httpbin.yaml
        oc apply -f https://raw.githubusercontent.com/maistra/istio/maistra-2.1/samples/httpbin/httpbin-gateway.yaml
        
== travel-agency 

Deployments see https://kiali.io/documentation/latest/tutorial/#03-traffic-shifting[Kiali Tutorial]

* Create namespaces

	oc new-project travel-agency
	oc new-project travel-portal
	oc new-project travel-control

* Create deployments

	oc apply -f <(curl -L https://raw.githubusercontent.com/kiali/demos/master/travels/travel_agency.yaml) -n travel-agency
	oc apply -f <(curl -L https://raw.githubusercontent.com/kiali/demos/master/travels/travel_portal.yaml) -n travel-portal
	oc apply -f <(curl -L https://raw.githubusercontent.com/kiali/demos/master/travels/travel_control.yaml) -n travel-control
	
* Add deployments in the mesh

	oc patch deployment/control -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-control
	
	oc patch deployment/travels -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-portal
	oc patch deployment/viaggi -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-portal
	oc patch deployment/voyages -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-portal		

	oc patch deployment/cars-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/discounts-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/flights-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency	
	oc patch deployment/hotels-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/insurances-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/mysqldb-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency	
	oc patch deployment/travels-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency	

* Apply initial mesh configs

	oc apply -f travel-agency/0-initial-service-mesh-config.yaml
	
== greetings-client-service
	
* Create namespaces	

	oc new-project greetings-client 
	oc new-project greetings-service


* Add deployments in the mesh

  ** Add `rest-greeting-remote` service in the mesh

	oc project greetings-service
	cd ../coded-services/quarkus-rest-greeting-remote
	mvn clean package -Dquarkus.kubernetes.deploy=true -DskipTests 
	oc patch dc/rest-greeting-remote -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n greetings-service

  *** Define Remote Service Cluster location of deployment message

	oc set env dc/rest-greeting-remote GREETING_LOCATION='Local Cluster'  (Default)
	oc set env dc/rest-greeting-remote GREETING_LOCATION='Remote Cluster' (oc rollout latest dc/rest-greeting-remote)
	oc rollout latest dc/rest-greeting-remote -n greetings-service

  ** Add `rest-client-greeting` service in the mesh

        cd ../coded-services/quarkus-rest-client-greeting
	oc project greetings-client
	mvn clean package -Dquarkus.kubernetes.deploy=true -DskipTests 
	oc patch dc/rest-client-greeting -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n greetings-client

  *** Define local/external service location of `rest-greeting-remote` service
  
* Build into an image and push to quay.io

        cd coded-services/quarkus-rest-client-greeting	
	podman build -f src/main/docker/Dockerfile.jvm -t quay.io/skoussou/rest-client-greeting:1.0.0 .
	podman push quay.io/skoussou/rest-client-greeting:1.0.0


.Remote Service Location Setting on `greetings-client`  deployment
====
[cols="2*^",options="header"]
|===
|How To Use
|Set Value

|*Default*
|oc set env dc/rest-client-greeting GREETINGS_SVC_LOCATION=http://rest-greeting-remote.greetings-service.svc.cluster.local:8080 

|oc rollout latest dc/rest-client-greeting
|oc set env dc/rest-client-greeting GREETINGS_SVC_LOCATION='http://hello.remote.com' and add in the dc/rest-greeting-remote 
      hostAliases:		
        - ip: 127.0.0.1			
          hostnames:			
            - hello.client.com		
        - ip: 10.1.2.3			
          hostnames:			

|===
====

	oc rollout latest dc/rest-greeting-remote -n greetings-service


* Apply initial Deployment `Service Mesh` configs

  ** Client Side
  
	oc patch dc/rest-client-greeting -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n greetings-client
	oc rollout latest dc/rest-client-greeting -n greetings-client

  ** Remote Service Side
  
	oc patch dc/rest-greeting-remote -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n greetings-service
	oc rollout latest dc/rest-greeting-remote -n greetings-service
	
* Apply for local cluster setup `Service Mesh` configs to enable external access

	oc apply -f ISTIO-YAML/istio-hello-client-gateway.yaml	
	oc apply -f ISTIO_YAML/istio-helloworld-gateway.yaml		

* Call `rest-client-greeting` via Service Mesh
  
        curl -X GET http://$(oc get route istio-ingressgateway -o jsonpath='{.spec.host}' -n <istio-system-control-plane>)/say/goodday-to/Stelios
	
* Call `rest-greeting-remote` via Service Mesh	

        curl -X GET http://$(oc get route hello-remote -o jsonpath='{.spec.host}' -n <istio-system-control-plane>)/hello/Stelios

* Build into an image and push to quay.io

        cd coded-services/quarkus-rest-greeting-remote	
	podman build -f src/main/docker/Dockerfile.jvm -t quay.io/skoussou/rest-greeting-remote:1.0.0 .
	podman push quay.io/skoussou/rest-greeting-remote:1.0.0

== bookinfo 

* maistra

	oc new-project bookinfo
	# if there is no SMMR do the following already an SMMR do the 2nd to patch it	
	../scripts/create-membership.sh istio-system basic bookinfo
	oc patch smmr default --type='json' -p='[{"op": "add", "path": "/spec/members/-", "value":"bookinfo"}]' -n istio-system-certs
	oc apply -f https://raw.githubusercontent.com/maistra/istio/maistra-2.1/samples/bookinfo/platform/kube/bookinfo.yaml
	oc apply -f https://raw.githubusercontent.com/maistra/istio/maistra-2.1/samples/bookinfo/networking/bookinfo-gateway.yaml
	curl -s "http://$(oc get route istio-ingressgateway -o jsonpath='{.spec.host}' -n istio-system-certs)/productpage" | grep -o "<title>.*</title>"

* istio

	https://github.com/kiali/kiali/blob/master/hack/istio/install-sm2.sh#L566-L579

== hello-openshift

* Deploy `hello-openshift` service

	cd Scenario-0-Deploy-In-ServiceMesh/hello-openshift
	deploy-hello-openshift.sh <APP_NAMESPACE> <ISTIO_NAMESPACE>
	
* Add *_http_* external access to `hello-openshift` service on Service Mesh	

	add-hello-openshift-gw-vs-for-http.sh <APP_NAMESPACE>


== opentracing-hello

=== Opentracing with Jaeger DaemonSet Agent

	cd coded-services/quarkus-opentracing/ISTIO-YAML
	./create-quarkus-opentracing-jaeger-daemonset.sh <SM_NAMESPACE <SM Tenant Name> <APPLICATION_NAMESPACE> <INGRESS GATEWAY ROUTE>
	eg. ./create-quarkus-opentracing-jaeger-daemonset.sh istio-system basic test-hello istio-ingressgateway-istio-system.apps.cluster-6g6f4.6g6f4.sandbox960.opentlc.com

=== Opentracing with Jaeger Agent Sidecar
	
	cd coded-services/quarkus-opentracing/ISTIO-YAML
	./create-quarkus-opentracing-jaeger-sidecar.sh <SM_NAMESPACE <SM Tenant Name> <APPLICATION_NAMESPACE> <INGRESS GATEWAY ROUTE>	
	eg. ./create-quarkus-opentracing-jaeger-sidecar.sh istio-system basic test-hello istio-ingressgateway-istio-system.apps.cluster-6g6f4.6g6f4.sandbox960.opentlc.com
	
=== Create Container Image and push to quay.io

	cd coded-services/quarkus-opentracing/
	./create-quarkus-opentracing-docker-image.sh <quay.io username> <image version id> 





	
