= Various Deployments for the ServiceMesh
:toc:

== httpbin

	oc new-project httpbin
	oc project httpbin
	oc apply -f https://raw.githubusercontent.com/maistra/istio/maistra-2.1/samples/httpbin/httpbin.yaml
        oc apply -f https://raw.githubusercontent.com/maistra/istio/maistra-2.1/samples/httpbin/httpbin-gateway.yaml
        
== travel-agency 

Deployments see https://kiali.io/documentation/latest/tutorial/#03-traffic-shifting[Kiali Tutorial]

* Create namespaces

	oc new-project travel-agency
	oc new-project travel-portal
	oc new-project travel-control

* Create deployments

	oc apply -f <(curl -L https://raw.githubusercontent.com/kiali/demos/master/travels/travel_agency.yaml) -n travel-agency
	oc apply -f <(curl -L https://raw.githubusercontent.com/kiali/demos/master/travels/travel_portal.yaml) -n travel-portal
	oc apply -f <(curl -L https://raw.githubusercontent.com/kiali/demos/master/travels/travel_control.yaml) -n travel-control
	
* Add deployments in the mesh

	oc patch deployment/control -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-control
	
	oc patch deployment/travels -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-portal
	oc patch deployment/viaggi -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-portal
	oc patch deployment/voyages -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-portal		

	oc patch deployment/cars-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/discounts-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/flights-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency	
	oc patch deployment/hotels-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/insurances-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/mysqldb-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency	
	oc patch deployment/travels-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency	

* Apply initial mesh configs

	oc apply -f travel-agency/0-initial-service-mesh-config.yaml
	
== greetings-client-service
	
* Create namespaces	

	oc new-project greetings-client 
	oc new-project greetings-service


* Add deployments in the mesh

  ** Add `rest-greeting-remote` service in the mesh

	oc project greetings-service
	cd ../coded-services/quarkus-rest-greeting-remote
	mvn clean package -Dquarkus.kubernetes.deploy=true -DskipTests 
	oc patch dc/rest-greeting-remote -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n greetings-service

  *** Define Remote Service Cluster location of deployment message

	oc set env dc/rest-greeting-remote GREETING_LOCATION='Local Cluster'  (Default)
	oc set env dc/rest-greeting-remote GREETING_LOCATION='Remote Cluster' (oc rollout latest dc/rest-greeting-remote)
	oc rollout latest dc/rest-greeting-remote -n greetings-service

  ** Add `rest-client-greeting` service in the mesh

        cd ../coded-services/quarkus-rest-client-greeting
	oc project greetings-client
	mvn clean package -Dquarkus.kubernetes.deploy=true -DskipTests 
	oc patch dc/rest-client-greeting -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n greetings-client

  *** Define local/external service location of `rest-greeting-remote` service

.Remote Service Location Setting on `greetings-client`  deployment
====
[cols="2*^",options="header"]
|===
|How To Use
|Set Value

|*Default*
|oc set env dc/rest-client-greeting GREETINGS_SVC_LOCATION=http://rest-greeting-remote.greetings-service.svc.cluster.local:8080 

|oc rollout latest dc/rest-client-greeting
|oc set env dc/rest-client-greeting GREETINGS_SVC_LOCATION='http://hello.remote.com' and add in the dc/rest-greeting-remote 
      hostAliases:		
        - ip: 127.0.0.1			
          hostnames:			
            - hello.client.com		
        - ip: 10.1.2.3			
          hostnames:			

|===
====

	oc rollout latest dc/rest-greeting-remote -n greetings-service


* Apply initial Deployment `Service Mesh` configs

  ** Client Side
  
	oc patch dc/rest-client-greeting -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n greetings-client
	oc rollout latest dc/rest-client-greeting -n greetings-client

  ** Remote Service Side
  
	oc patch dc/rest-greeting-remote -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n greetings-service
	oc rollout latest dc/rest-greeting-remote -n greetings-service
	
	

* Call `rest-client-greeting` via Service Mesh
  
        curl -X GET http://$(oc get route istio-ingressgateway -o jsonpath='{.spec.host}' -n <istio-system-control-plane>)/say/goodday-to/Stelios
	
* Call `rest-greeting-remote` via Service Mesh	

        curl -X GET http://$(oc get route hello-remote -o jsonpath='{.spec.host}' -n <istio-system-control-plane>)/hello/Stelios


	
