= Various Deployments for the ServiceMesh
:toc:

== httpbin

	oc new-project httpbin
	oc project httpbin
	oc apply -f https://raw.githubusercontent.com/maistra/istio/maistra-2.1/samples/httpbin/httpbin.yaml
        oc apply -f https://raw.githubusercontent.com/maistra/istio/maistra-2.1/samples/httpbin/httpbin-gateway.yaml
        
== travel-agency 

Deployments see https://kiali.io/documentation/latest/tutorial/#03-traffic-shifting[Kiali Tutorial]

* Create namespaces

	oc new-project travel-agency
	oc new-project travel-portal
	oc new-project travel-control

* Create deployments

	oc apply -f <(curl -L https://raw.githubusercontent.com/kiali/demos/master/travels/travel_agency.yaml) -n travel-agency
	oc apply -f <(curl -L https://raw.githubusercontent.com/kiali/demos/master/travels/travel_portal.yaml) -n travel-portal
	oc apply -f <(curl -L https://raw.githubusercontent.com/kiali/demos/master/travels/travel_control.yaml) -n travel-control
	
* Add deployments in the mesh

	oc patch deployment/control -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-control
	
	oc patch deployment/travels -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-portal
	oc patch deployment/viaggi -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-portal
	oc patch deployment/voyages -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-portal		

	oc patch deployment/cars-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/discounts-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/flights-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency	
	oc patch deployment/hotels-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/insurances-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/mysqldb-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency	
	oc patch deployment/travels-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency	

* Apply initial mesh configs

	oc apply -f travel-agency/0-initial-service-mesh-config.yaml
	
== greetings-client-service
	
*Note:* Scripts can be found in link:../coded-services/quarkus-rest-client-greeting[quarkus-rest-client-greeting] and link:../coded-services/quarkus-rest-greeting-remote[quarkus-rest-greeting-remote]
	
* Create Deployments & Service Mesh Configs	

  ** In *Service Clusters* (_must match SMCP SMMR namespace details_) add `rest-greeting-remote` service in the mesh
  *** *Service Cluster 1*
	
	./create-greeting-remote-service.sh <SMCP Namspace> <SMMR namespace> <SMCP Ingress Gateway URL> <REMOTE Service Route HostName> <Greeting Cluster Specific Message>
	eg. ./create-greeting-remote-service.sh istio-system-tenant-6 greetings-service-6 istio-ingressgateway-istio-system-tenant-6.apps.cluster-ac6a.ac6a.sandbox1173.opentlc.com greeting.remote.com OCP-48-Cluster		

  *** *Service Cluster 2*

	./create-greeting-remote-service.sh <SMCP Namspace> <SMMR namespace> <SMCP Ingress Gateway URL> <REMOTE Service Route HostName> <Greeting Cluster Specific Message>
	eg. ./create-greeting-remote-service.sh istio-system-tenant-6 greetings-service-6 istio-ingressgateway-istio-system-tenant-6.apps.rosa-e532.qxhy.p1.openshiftapps.com greeting.remote.com Rosa-Remote-Cluster
	
  ** In *Client Clusters* (_must match SMCP SMMR namespace details_) add `rest-greeting-client` service in the mesh
	
	./create-greeting-client.sh <SMCP Namspace> <SMMR namespace> <SMCP Ingress Gateway URL> <Remote 1 - SMCP Ingress Gateway URL>  <Remote 2 - SMCP Ingress Gateway URL> <REMOTE Service Route HostName>
	eg. ./create-greeting-client.sh istio-system-tenant-6 greetings-client-6 istio-ingressgateway-istio-system-tenant-6.apps.cluster-vnm7p.vnm7p.sandbox1792.opentlc.com istio-ingressgateway-istio-system-tenant-6.apps.cluster-ac6a.ac6a.sandbox1173.opentlc.com istio-ingressgateway-istio-system-tenant-6.apps.rosa-e532.qxhy.p1.openshiftapps.com greeting.remote.com


* How is local/external service location of `rest-greeting-remote` service is defined for `rest-client-greeting`

.Remote Service Location Setting on `rest-client-greeting`  deployment
====
[cols="2*^",options="header"]
|===
|How To Use
|Set Value

|*Default*
|oc set env dc/rest-client-greeting GREETINGS_SVC_LOCATION=http://rest-greeting-remote.greetings-service.svc.cluster.local:8080 

|oc rollout latest dc/rest-greeting-remote
|oc set env dc/rest-client-greeting GREETINGS_SVC_LOCATION='http://hello.remote.com'

|===
====


* Test `rest-client-greeting` via mesh

  ** Calling directly service cluster deployments
  
	curl -X GET http://$(oc get route hello-remote -o jsonpath='{.spec.host}' -n <istio-system-control-plane-namespace>)/hello/Stelios        

  ** Calling client cluster deployments
	
	curl -X GET http://$(oc get route istio-ingressgateway -o jsonpath='{.spec.host}' -n <istio-system-control-plane-namespace>)/say/goodday-to/Stelios  
	
  **  Continuous execution and changes in availability of service in the clusters
  
  	watch -n 2 curl -i http://$(oc get route istio-ingressgateway -o jsonpath='{.spec.host}' -n <istio-system-control-plane-namespace>)/say/goodday-to/Stelios	
  	oc scale --replicas=0 dc rest-greeting-remote -n greetings-service-6
  	oc scale --replicas=1 dc rest-greeting-remote -n greetings-service-6
  	
  	
	
	
	


