= Various Deployments for the ServiceMesh
:toc:

== httpbin

	oc new-project httpbin
	oc project httpbin
	oc apply -f https://raw.githubusercontent.com/maistra/istio/maistra-2.1/samples/httpbin/httpbin.yaml
        oc apply -f https://raw.githubusercontent.com/maistra/istio/maistra-2.1/samples/httpbin/httpbin-gateway.yaml
        
== travel-agency 

Deployments see https://kiali.io/documentation/latest/tutorial/#03-traffic-shifting[Kiali Tutorial]

* Create namespaces

	oc new-project travel-agency
	oc new-project travel-portal
	oc new-project travel-control

* Create deployments

	oc apply -f <(curl -L https://raw.githubusercontent.com/kiali/demos/master/travels/travel_agency.yaml) -n travel-agency
	oc apply -f <(curl -L https://raw.githubusercontent.com/kiali/demos/master/travels/travel_portal.yaml) -n travel-portal
	oc apply -f <(curl -L https://raw.githubusercontent.com/kiali/demos/master/travels/travel_control.yaml) -n travel-control
	
* Add deployments in the mesh

	oc patch deployment/control -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-control
	
	oc patch deployment/travels -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-portal
	oc patch deployment/viaggi -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-portal
	oc patch deployment/voyages -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-portal		

	oc patch deployment/cars-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/discounts-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/flights-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency	
	oc patch deployment/hotels-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/insurances-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency
	oc patch deployment/mysqldb-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency	
	oc patch deployment/travels-v1 -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n travel-agency	

* Apply initial mesh configs

	oc apply -f travel-agency/0-initial-service-mesh-config.yaml
	
== greetings-client-server
	
* Create namespaces	

	oc new-project greetings-client
	oc new-project greetings-service

* Add deployments in the mesh

  ** Add `rest-greeting-remote` service in the mesh

	oc project greetings-service
	mvn clean package -Dquarkus.kubernetes.deploy=true -DskipTests 
	oc patch deployment/rest-greeting-remote -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n greetings-service

  *** Define local/external cluster location of deployment 

	oc set env dc/rest-greeting-remote GREETING_LOCATION='Local Cluster' (Default)
	oc set env dc/rest-greeting-remote GREETING_LOCATION='Remote Cluster'	(oc rollout latest dc/rest-greeting-remote)

  ** Add `rest-client-greeting` service in the mesh

	oc project greetings-client
	mvn clean package -Dquarkus.kubernetes.deploy=true -DskipTests 
	oc patch deployment/rest-client-greeting -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject": "true"}}}}}' -n greetings-client

  *** Define local/external service location of `rest-greeting-remote` service

	oc set env dc/rest-client-greeting GREETINGS_SVC_LOCATION=http://rest-greeting-remote.greetings-service.svc.cluster.local:8080 (Default)
	oc set env dc/rest-greeting-remote GREETINGS_SVC_LOCATION='http://hello.remote.com'	(oc rollout latest dc/rest-greeting-remote)

* Apply initial mesh configs

*TBD*

* Call `rest-client-greeting` via mesh

        curl -X GET http://$(oc get route istio-ingressgateway -o jsonpath='{.spec.host}' -n <istio-system-control-plane>)/say/goodday-to/Stelios
	


	
	
