= How to Configure the `istio-proxy`
:toc:

= Configure via annotations

== link:https://istio.io/latest/docs/reference/config/annotations/[proxy.istio.io/config] in a `Deployment`

* link:https://istio.io/latest/docs/reference/config/annotations/[proxy.istio.io/config] Overrides for the proxy configuration for this specific proxy. Available options can be found at https://istio.io/docs/reference/config/istio.mesh.v1alpha1/#ProxyConfig

----
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
        proxy.istio.io/config: |
          tracing: <1>
            zipkin: <2>
              address: zipkin.istio-system:9411 <3>
            sampling: 10 <4>
            custom_tags:
              http.header.portal:
                header:
                  name: portal
              http.header.device:
                header:
                  name: device
              http.header.user:
                header:
                  name: user
              http.header.travel:
                header:
                  name: travel
----

<1> Modify `istio-proxy` tracing configuration (see: link:https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Tracing[Tracing] for configuration options
<2> Utilize `zipkin` client
<3> link:https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#Tracing-Zipkin[Address configuration]
<4> Tracing Samples (10%)

== Annotations for Envoy Resource CPU/Limits

See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html-single/service_mesh#ossm-migrating-differences-annotation_ossm-upgrade[Annotation Changes in 2.x upgrade]

*   `sidecar.istio.io/proxyCPULimit` (replacing `sidecar.maistra.io/proxyCPULimit`) 
*   `sidecar.istio.io/proxyMemoryLimit` (replacing ``sidecar.maistra.io/proxyMemoryLimit`)

== Annotations on address/ports

See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html-single/service_mesh#ossm-migrating-differences-annotation_ossm-upgrade[Annotation Changes in 2.x upgrade]

*   `sidecar.istio.io/discoveryAddress` (*_is no longer supported_*) 
* Default 'discovery address' has moved from `pilot.<control_plane_namespace>.svc:15010` (or port `15011`, if `mtls` is enabled) to `istiod-<smcp_name>.<control_plane_namespace>.svc:15012`.
* The 'health status port' is no longer configurable and is hard-coded to `15021`. (ie. custom status port, for example, `status.sidecar.istio.io/port`, you must remove the override before moving the workload to a v2.0 control plane. Readiness checks can still be disabled by setting the status port to 0.)

== Annotations around Health Probes

* `sidecar.istio.io/rewriteAppHTTPProbers: "true"|"false"`: For the httpGet probes, set your deployments/deploymentConfigs with annotation sidecar.istio.io/rewriteAppHTTPProbers: "true" or a dedicated port for the probe that is not capture by the envoy will be needed. As if it is not set, then istio-proxy will identify this as traffic reaching the upstream host and will break the connections. When that annotation is present, then the probes are going to be rewritten and handled by the envoy and therefore the issue disappears and probes will work (see: link:https://access.redhat.com/solutions/6736921[After encrypting (mTLS ) a ServiceMesh control plane applications Liveness health check does not work ])
* Istio link:https://istio.io/latest/docs/ops/configuration/mesh/app-health-check/[Health Checking of Istio Services] suggests the opposite though

== Annotation to allow non-mesh Route Access to services

* `maistra.io/expose-route: "true"`: It is possible to use the OCP route from a non-mesh service on OCP Service Mesh. To do that, it is necessary to label the deployment with maistra.io/expose-route: "true" (see: link:https://access.redhat.com/solutions/6707431[Is it possible to use the OpenShift Container Platform routes from non-mesh services in a service mesh enlisted namespace? ]



# Configure via `ServiceMeshControlPlane`
