= Apply WASM Mesh Extension
:toc:

* ServiceMesh Version: 2.0
* Purpose: Extend the capabilities of the Mesh with a WASM Extension

== Setup ServiceMesh installation

* Pre-Requisites

`ServiceMesh` Operators Installation *TBD*

* Setup

1. Control Plane Namespace Creation

	oc new-project <istio-system-wasm-poc>

2. SMCP

	oc apply -f smcp-2.0.yaml
	
  ** or modify/apply the following
  
	apiVersion: maistra.io/v2
	kind: ServiceMeshControlPlane
	metadata:
	  name: <tenant-1>
	  namespace: <istio-system-wasm-poc>
	spec:
	  techPreview:
	    wasmExtensions:
	      enabled: true
	  tracing:
	    sampling: 10000
	    type: Jaeger
	  general:
	    logging:
	      logAsJSON: true
	  profiles:
	    - default
	  proxy:
	    accessLogging:
	      file:
		name: /dev/stdout
	  policy:
	    type: Istiod
	  addons:
	    grafana:
	      enabled: true
	    jaeger:
	      install:
		storage:
		  type: Memory
	    kiali:
	      enabled: true
	    prometheus:
	      enabled: true
	  version: v2.0
	  telemetry:
	    type: Istiod

  ** Reset

	oc delete -f smcp-2.0.yaml

3. SMBR

	oc apply -f smmr.yaml

  ** Reset	

	oc delete -f smmr.yaml

4. ServiceMeshExtension

	oc apply -f sm-extension.yaml	

  ** Reset	

	oc delete -f sm-extension.yaml	

	
== Setup Mesh Deployments

* Create

	oc apply -f httpbin-namespace.yaml
	oc project httpbin
	oc apply -f https://raw.githubusercontent.com/maistra/istio/maistra-2.1/samples/httpbin/httpbin.yaml
        oc apply -f https://raw.githubusercontent.com/maistra/istio/maistra-2.1/samples/httpbin/httpbin-gateway.yaml

* Remove 	
	oc delete -f httpbin-namespace.yaml 	

	
== Testing	

* Before Applying WASM `ServiceMeshExtension` (no `custom-header: test` header)

----
curl -i -X GET "http://istio-ingressgateway-istio-wasm-poc.apps.cluster-6tzwm.6tzwm.sandbox256.opentlc.com/response-headers?freeform=" -H "accept: application/json"
HTTP/1.1 200 OK
server: istio-envoy
date: Tue, 12 Oct 2021 09:26:55 GMT
content-type: application/json
content-length: 87
freeform: 
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 5
set-cookie: 7166af6d5626ff0abdebe2a0badfa327=cc90fe62b70bb43bfc57828493faca96; path=/; HttpOnly
cache-control: private

{
  "Content-Length": "87", 
  "Content-Type": "application/json", 
  "freeform": ""
}
----

* After Applying WASM `ServiceMeshExtension` (has `custom-header: test` header)

** `oc logs -f httpbin-599849d486-qkrw4 -c istio-proxy` (look for envoy proxy ready)
** Retest

----
curl -i -X GET "http://istio-ingressgateway-istio-wasm-poc.apps.cluster-6tzwm.6tzwm.sandbox256.opentlc.com/response-headers?freeform=" -H "accept: application/json"
HTTP/1.1 200 OK
server: istio-envoy
date: Tue, 12 Oct 2021 09:24:43 GMT
content-type: application/json
content-length: 87
freeform: 
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 2
custom-header: test
set-cookie: 7166af6d5626ff0abdebe2a0badfa327=cc90fe62b70bb43bfc57828493faca96; path=/; HttpOnly
cache-control: private

{
  "Content-Length": "87", 
  "Content-Type": "application/json", 
  "freeform": ""
}
----

== Resources

* https://docs.openshift.com/container-platform/4.6/service_mesh/v2x/ossm-extensions.html#webassembly-extensions[WebAssembly extensions]
* https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/v0.1.4/examples/http_auth_random.rs[proxy-wasm-rust-sdk]= Apply WASM Mesh Extension



